version: '3'

services:
  lion-app:
    container_name: lion-app-dc
    image: lion-cr.kr.ncr.ntruss.com/lion-app:latest
    ports:
      - 8000:8000
    volumes:
      - ~/.aws:/root/.aws:ro
      - "staticfiles:/var/www/html/static"
    command:
      - "/start"
    env_file:
      - ./.envs/prod/django
      - ./.envs/prod/db
      - ./.envs/prod/server
    environment:
      - AWS_SECRET_NAME=like/lion/prod

  nginx:
    depends_on:
      - lion-app
    container_name: lion-nginx-dc
    build:
      context: .
      dockerfile: Dockerfile.nginx_ubt
    image: lion-nginx
    ports:
      - "8888:80"
    volumes:
      - "staticfiles:/var/www/html/static"
    env_file:
      - ./.envs/prod/server

volumes:
  staticfiles:
