# Generated by Django 4.2.3 on 2023-08-30 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Forum", "0003_topicgroupuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image_url",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="topicgroupuser",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="Forum.topic",
            ),
        ),
    ]
