name: workflow run

on:
    workflow_run:
        workflows: ["call workflow"]
        types:
            - completed

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - run: echo "workflow run triggered"
            