name: CD using Docker Image

on:
    push:
        branches:
            - 'main'

env:
    IMAGE_TAG: ${{ vars.NCR_REGISTRY }}/lion-app:latest

jobs:
    build-and-push:
        name: Build and Push Image
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up Docker buildx
              uses: docker/setup-buildx-action@v2
            - name: Login to NCR
              uses: docker/login-action@v2
              with:
                registry: ${{ vars.NCR_REGISTRY }}
                username: ${{ secrets.NCR_ACCESS_KEY_ID }}
                password: ${{ secrets.NCR_SECRET_KEY }}
            - name: Build and Push
              uses: docker/build-push-action@v4
              with:
                context: lion_app
                tags: ${{ env.IMAGE_TAG }}
                push: true

    deployment:
        needs: build-and-push
        name: deploy
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: pull and run the image
              uses: appleboy/ssh-action@v1.0.0
              with:
                host: ${{ secrets.HOST }}
                username: ${{ secrets.USERNAME }}
                password: ${{ secrets.PASSWORD }}
                script: |
                    cd lion_django_app
                    docker login \
                    ${{ vars.NCR_REGISTRY }} \
                    -u ${{ secrets.NCR_ACCESS_KEY_ID }} \
                    -p ${{ secrets.NCR_SECRET_KEY }}
                    docker pull ${{ env.IMAGE_TAG }}
                    docker-compose -f docker-compose.prod.yml restart lion-app
            - name: echo IMAGE_TAG
              run: echo $IMAGE_TAG
